### ISSUE TITLE
integrate salesforce with sign up flow

### ISSUE THREAD

**Issue by heyjay44** [fireproof-storage/dashboard#17]
**Phase 1: Salesforce Integration**
- [x] @necrodome to research Salesforce integration
- [x] @necrodome testing and integrating
- [x] @necrodome to work with Anna to ensure sign ups pre-Salesforce integration are in Salesforce

**Phase 2: Welcome Email**
- [x] @necrodome  to export the current users to Meghan so she can send out the first welcome email
- [x] @necrodome to send out the first email to initial users that weren't part of updated sign up flow

**Phase 3: Automate Welcome Email**
- [x] @AnnaFireproof  to research and finalise sign up flow

**Comment by AnnaFireproof** [comment]
@heyjay44 the process diagram is below and in Notion at (https://www.notion.so/Flow-charts-for-processes-1469e5107ccb80c18cccff25a538ac60?pvs=4) need folks to review and I will make any edits. 
![2024-11-22_17-03-44](https://github.com/user-attachments/assets/1b17fc3d-9e12-4faa-9a18-44290e95c42a)

**Comment by necrodome** [comment]
@heyjay44  @AnnaFireproof this is up and running.
@AnnaFireproof pushed all current users to Salesforce.
